# Generated by Django 5.2 on 2025-05-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10000)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('featured', models.BooleanField(null=True)),
            ],
        ),
    ]
